- app/assets/scripts/a11n/rules.js
- app/assets/scripts/components/documents/document-download-menu.js
Resolves https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/342
Restricts Journal download to contributors and previewers
> Limit journal download

- app/assets/scripts/components/about/index.js
Resolves #473
- Updates text according to [feedback document](https://docs.google.com/document/d/1cePfusnaVvuGL1WbzflkaOPVFKi2-W_HOFqgseiyZHA/edit#heading=h.b98577nyf2jn)
- Links help page
> Update about page

- .github/workflows/deploy-prod.yml
This was setup to deploy the current code to the GCC S3 bucket.
This bucket will be the production bucket once the testing is complete.
> Update prod branch

- app/assets/scripts/components/common/page-header.js
- app/assets/scripts/components/documents/document-headline.js
- app/assets/scripts/components/documents/hub/index.js
- app/assets/scripts/components/documents/single-view/index.js
Contributes to https://github.com/NASA-IMPACT/nasa-apt/issues/472
- Changes the nav label from Documents to ATBDs
> Change nav: Documents to ATBDs

- app/assets/scripts/components/documents/single-edit/local-store/index.js
- app/assets/scripts/components/slate/plugins/common/with-simple-modal.js
- app/assets/scripts/components/slate/plugins/equation/equation-editor.js
- app/assets/scripts/components/slate/plugins/equation/equation-element.js
- app/assets/scripts/components/slate/plugins/equation/equation-modal.js
- app/assets/scripts/components/slate/plugins/equation/index.js
- app/assets/scripts/components/slate/plugins/equation/with-equation-modal.js
- app/assets/scripts/components/slate/plugins/reference/with-reference-modal.js
Implements https://github.com/NASA-IMPACT/nasa-apt/issues/502
Implements adding inline equations
- Extends the equation editor so inline equations can be selected
- Extends the Equation component so inline equations can be displayed in the text
> Equation popup inline

- app/assets/scripts/components/common/forms/field-atbd-alias.js
Fixes https://github.com/NASA-IMPACT/nasa-apt/issues/507
**Root cause**
The alias is automatically created and set whenever a document title is edited. One exception is when the user has previously edited the alias to prevent overwriting manually created aliases. Currently, we're identifying an edit by checkout `touched.alias` assuming that when the user focussed on a field and then blur that there has been an edit. 
This isn't necessarily the case, leading to a strange behaviour where I can first focus the alias field and then edit the document title, so we end up without an alias. 
**Solution**
With this change, we're now checking that the alias matches the expected alias we would get from the title _before_ the title was edited, indicating an edit to alias that deviates from …
> Check for changed alias value

- app/assets/scripts/config/production.js
- package.json
Updates production config for new environment
> Update production config

- .github/workflows/deploy-prod.yml
Update the production deploy script
> Update production deploy

- package.json
v2.4.1-beta
---
- 🦗 
- 🦗 
- Update the production deployment script
> v2.4.1-beta

- .babelrc
- .eslintrc
- .github/workflows/checks.yml
- cypress.config.js
- cypress/e2e/home/render.js
- cypress/plugins/index.js
- cypress/support/commands.js
- cypress/support/e2e.js
- cypress/support/login.js
- package.json
- yarn.lock
Preparing for future work where we need to add tests, also we should build a habit of writing tests for the features we build. 
This PR sets up Cypress and adds one simple test.
> Add Cypress

- app/assets/scripts/components/dashboard/use-document-menu-action.js
- app/assets/scripts/components/documents/document-actions-menu.js
- app/assets/scripts/components/documents/document-changelog-modal.js
- app/assets/scripts/components/documents/single-view/index.js
- app/assets/scripts/components/documents/use-document-modals.js
- app/assets/scripts/config.js
- app/assets/scripts/config/test.js
- cypress/e2e/documents/changelog.js
- cypress/fixtures/server/atbd-versions.json
- cypress/fixtures/server/atbd.json
- gulpfile.js
Implements https://github.com/NASA-IMPACT/nasa-apt/issues/527
- Adds a new options to the context menu to view changeling and download PDFs
- Clicking the button opens a modal listing all versions, their version description, and the download buttons 
- Removes existing download button
Test this with https://github.com/NASA-IMPACT/nasa-apt/pull/546
> Adds ATBD changelogs

- app/assets/scripts/components/documents/document-tracker-modal.js
- app/assets/scripts/config.js
- app/assets/scripts/config/test.js
- cypress/e2e/document/create.js
- cypress/fixtures/server/atbd-create.json
- cypress/fixtures/server/atbd-new.json
- cypress/fixtures/server/atbd-version-new.json
- cypress/fixtures/server/atbds.json
- cypress/fixtures/server/stats-new.json
- cypress/fixtures/server/stats.json
Add test and fixtures for the create-ATBD journey
> Add create-ATBD test

- app/assets/scripts/config/staging.js
Updating the staging urls for the new stack deployment.
> updates for staging

- app/assets/scripts/components/comment-center/comment-entry.js
- app/assets/scripts/components/comment-center/comment-form.js
- app/assets/scripts/components/comment-center/index.js
Contributes to https://github.com/NASA-IMPACT/nasa-apt/issues/456
- Allows selecting all curators to be notified when posting a comment
- Highlights comments from curators
Test together with https://github.com/NASA-IMPACT/nasa-apt/pull/560
> Curator comments

- app/assets/scripts/components/documents/document-download-menu.js
- app/assets/scripts/components/documents/single-view/index.js
Implements @aboydnw's [comment](https://github.com/NASA-IMPACT/nasa-apt/issues/527#issuecomment-1224590461)
Add PDF download button, limiting the options to the current document version
> Add download PDF button

- app/assets/scripts/components/documents/document-changelog-modal.js
- cypress/e2e/document/changelog.js
Adds download options for all versions to changelog
> Changelog download

- app/assets/scripts/components/common/toasts.js
- app/assets/scripts/components/contacts/contact-actions-menu.js
- cypress/e2e/contacts/create.js
- cypress/e2e/contacts/delete.js
- cypress/e2e/contacts/edit.js
- cypress/e2e/document/changelog.js
- cypress/fixtures/server/contacts/create.json
- cypress/fixtures/server/contacts/list.json
- cypress/fixtures/server/contacts/single.json
Adds tests for contacts (creating, editing, deleting)
> Contact tests

- app/assets/scripts/components/documents/single-edit/use-submit.js
Addresses point 4 in the comment on changelog changes: https://github.com/NASA-IMPACT/nasa-apt/issues/527#issuecomment-1245963380
> Send alias, it's now validated in the backend

- app/assets/scripts/components/about/index.js
- app/assets/scripts/components/common/feedback-form.js
- app/assets/scripts/components/common/page-header.js
- app/assets/scripts/config/production.js
- app/index.html
Fix https://github.com/NASA-IMPACT/nasa-apt/issues/557
> Replace feedback form with google form

- app/assets/scripts/components/about/index.js
- app/assets/scripts/components/common/feedback-form.js
- app/assets/scripts/components/common/page-header.js
- app/assets/scripts/components/documents/single-edit/use-submit.js
- app/assets/scripts/config/production.js
- app/index.html
PR merges `develop` to `main` for deployment to MCP S3 bucket for APT.
> Merge replace feedback #401 with main, deploy to MCP

- app/assets/scripts/components/documents/pdf-preview/index.js
- app/assets/scripts/components/documents/single-view/document-body.js
- app/assets/scripts/components/documents/single-view/document-content.js
- app/assets/scripts/components/documents/single-view/index.js
- app/assets/scripts/components/documents/single-view/scroll-manager.js
- app/assets/scripts/main.js
- app/assets/scripts/styles/global.js
- app/index.html
- package.json
- static/pdf-preview-styles.css
- yarn.lock
We can see the paged preview just by adding `/pdf-preview` to the view url (eg: `/documents/46/v1.0/pdf-preview`)
Note to @sunu: It takes a small amount of time for the pagedjs to convert the preview into the paged view, let me know if there's a way we can add some triggers to let you know that the conversion has been completed.
We can tweak the preview as per the requirement.
CC: @wrynearson
> PDF Preview

- app/assets/scripts/a11n/signin.js
- app/assets/scripts/components/common/toasts.js
- app/assets/scripts/context/user.js
- package.json
- yarn.lock
_Upstream: https://github.com/NASA-IMPACT/nasa-apt/issues/608_
NOTE: When user sign's in, we prompt the user to set-up the MFA. Once it has been set-up the user would require to use the MFA from the next sign-in
> Implement MFA

- app/assets/scripts/components/documents/document-download-menu.js
- app/assets/scripts/components/documents/pdf-preview/index.js
- static/pdf-preview-styles.css
@sunu We'll have an empty div when pdf preview is ready
```html
<div id='pdf-preview-ready' />
```
> Add an empty div to mark the pdf preview completion

- app/assets/scripts/utils/references.js
Addresses https://github.com/NASA-IMPACT/nasa-apt/issues/602
> Fix bibtex import issues

- app/assets/scripts/components/documents/pdf-preview/index.js
- app/assets/scripts/components/documents/single-view/document-body.js
- app/assets/scripts/styles/global.js
- static/pdf-preview-styles.css
Related to: https://github.com/NASA-IMPACT/nasa-apt/issues/642
Let's also make sure heading actions (i.e. Show comments) are visible in view mode (i.e. only hidden in pdf-preview mode)
> Add table of contents

- app/assets/scripts/components/common/page-footer.js
- app/assets/scripts/components/common/page-header.js
- app/assets/scripts/components/dashboard/index.js
- app/assets/scripts/components/documents/hub/index.js
- app/assets/scripts/components/documents/pdf-preview/index.js
- app/assets/scripts/components/documents/single-view/document-content.js
- app/assets/scripts/components/documents/single-view/index.js
- app/assets/scripts/components/home/index.js
- app/assets/scripts/components/slate/editor.js
- app/assets/scripts/components/slate/plugins/list/index.js
- app/assets/scripts/styles/card.js
- app/assets/scripts/styles/constrainer.js
- app/assets/scripts/styles/global.js
- app/assets/scripts/styles/inpage.js
- app/assets/scripts/styles/typography/details-list.js
- app/assets/scripts/styles/typography/prose.js
- app/assets/scripts/styles/universal-gridder.js
- static/pdf-preview-styles.css
Related to: https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/417
> Make pdf preview consistent with print mode

- app/assets/scripts/styles/global.js
- static/pdf-preview-styles.css
Addresses https://github.com/NASA-IMPACT/nasa-apt/issues/620
> Add intendation to paragraphs in pdf-preview

- README.md
_Github doesn't allow PR template selection the same way that it is possible with issues._  
_Preview this and select the appropriate template:_
- [Version Release](?template=version_release.md)
- _Alternatively delete and start empty_
> capitalize some letters

- app/assets/scripts/components/documents/pdf-preview/index.js
- app/assets/scripts/components/documents/single-view/document-content.js
- app/assets/scripts/components/documents/single-view/document-title.js
- app/assets/scripts/styles/global.js
Partially addresses: https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/443
@wrynearson Please also verify that view mode is working same as before
> Move TOC after title page in pdf preview

- app/assets/scripts/components/documents/pdf-preview/index.js
- app/assets/scripts/components/documents/single-view/document-body.js
- app/assets/scripts/styles/global.js
- Remove abstract and plain language summary from toc
- Add line break before version description
- Add spacing between references in pdf preview
- Add line break before references section
- https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/445
- https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/446
> Improve pdf preview formatting

- app/assets/scripts/styles/global.js
Upstream: https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/446
> Add hanging indentation for the references in pdf preview

- app/assets/scripts/components/comment-center/comment-entry.js
Addresses
- https://github.com/NASA-IMPACT/nasa-apt/issues/656
> Disable comment update button for curator(other's comment)

- app/assets/scripts/components/documents/single-edit/check-lock.js
Should address: https://github.com/NASA-IMPACT/nasa-apt/issues/594
> Simplify mechanism to acquire and clear lock

- content/help-documentation/latex.md
Upstream: https://github.com/NASA-IMPACT/nasa-apt/issues/672
> Latex_update

- app/assets/scripts/components/documents/citation.js
- app/assets/scripts/components/documents/single-edit/step-algo-implementation.js
- app/assets/scripts/components/documents/single-edit/step-contacts/index.js
- app/assets/scripts/components/documents/single-edit/step-identifying-information.js
- app/assets/scripts/components/documents/single-edit/step-references/references-manager.js
Upstream: https://github.com/NASA-IMPACT/nasa-apt/issues/741
> More UI text updates

- app/assets/scripts/components/documents/single-edit/step-pdf-closeout.js
- app/assets/scripts/components/documents/single-edit/steps.js
Addresses https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/494
> Fix status calculation for pdf type atbd

- app/assets/scripts/components/documents/new-atbd-modal.js
- app/assets/scripts/components/documents/single-edit/check-lock.js
- app/assets/scripts/components/documents/single-edit/step-attachment.js
- app/assets/scripts/components/documents/single-edit/use-document-create.js
- app/assets/scripts/context/atbds-list.js
- Add alias field in the document create modal
- Show message during the pdf upload
- Block upload for the files other that `application/pdf` mime type
Addresses: https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/489, https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/490, https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/491
> Add alias field in the document create modal

- content/help-documentation/APT_QuickStart.md
- content/help-documentation/apt.md
Upstream: https://github.com/NASA-IMPACT/nasa-apt/issues/530 and https://github.com/NASA-IMPACT/nasa-apt/issues/749
Reviewer could see if links work, but most of them will redirect to the production website. Otherwise, IMPACT will review the content and links.
> Add and update user guides

- app/assets/scripts/components/documents/new-atbd-modal.js
- app/assets/scripts/components/new-atbd/index.js
Upstream: https://github.com/NASA-IMPACT/nasa-apt/issues/674#issuecomment-1598895416
> Add template PDF workflow video to create ATBD modal tooltip

- app/assets/scripts/components/new-atbd/index.js
Upstream: https://github.com/NASA-IMPACT/nasa-apt/issues/732#issuecomment-1600907002
Removed the PDF drawback `Requires external ATBD review` and the APT user interface drawback `User interface updates and improvements may cause intermitted disruptions`
> Update benefit/drawback table

- app/assets/scripts/components/new-atbd/index.js
- content/help-documentation/quickstart.md
Fixing incorrect link on production with our most recent deployment.
> Change quickstart filename, link

- .github/workflows/checks.yml
- app/assets/scripts/components/documents/single-view/document-body.js
- app/assets/scripts/components/slate/editor.js
- app/assets/scripts/components/slate/safe-read-editor.js
Upstream: https://github.com/NASA-IMPACT/nasa-apt/issues/682
> Add Significance Discussion section from Journal Details to pdf

- app/assets/scripts/components/slate/plugins/image/toolbar-image-button.js
Addresses: https://github.com/NASA-IMPACT/nasa-apt/issues/587
> Rescale image before upload

- app/assets/scripts/components/documents/single-edit/step-closeout/journal-details.js
- app/assets/scripts/components/documents/single-edit/step-pdf-closeout.js
- app/assets/scripts/components/documents/single-view/document-body.js
- playwright/fixtures/register.js
- playwright/fixtures/server/pdf/atbd-pdf-stats.json
- playwright/fixtures/server/pdf/atbd-pdf-version.json
- playwright/fixtures/server/pdf/atbd-pdf.json
- tests/pdfMode/closeout.spec.js
> Add journal details section to closeout step

- app/assets/scripts/utils/references.js
> Fixes to reference and citation styling

- app/assets/scripts/components/documents/single-edit/step-references/reference-form-fields.js
Upstream: https://github.com/NASA-IMPACT/nasa-apt/issues/784#issuecomment-1665561837
> Update Authors reference form helper message

- app/assets/scripts/components/documents/single-edit/local-store/index.js
- app/assets/scripts/components/documents/single-edit/sections.js
- app/assets/scripts/components/documents/single-edit/step-contacts/index.js
- app/assets/scripts/components/documents/single-edit/steps.js
- app/assets/scripts/components/documents/single-view/document-body.js
- app/assets/scripts/utils/common.js
Upstream: https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/514
> Add reviewer information in Contact section

- app/assets/scripts/components/common/confirmation-prompt.js
- app/assets/scripts/components/documents/document-actions-menu.js
- playwright/fixtures.ts
- playwright/fixtures/register.js
- playwright/fixtures/server/atbd-new.json
- playwright/fixtures/server/atbd-version-new.json
- playwright/fixtures/server/stats-new.json
- tests/documents/delete.spec.js
Fix for https://github.com/NASA-IMPACT/nasa-apt/issues/548
Adds tests for different roles and use cases.
> Fix delete button behavior for draft documents

- content/help-documentation/apt.md
- content/help-documentation/quickstart.md
_Github doesn't allow PR template selection the same way that it is possible with issues._  
_Preview this and select the appropriate template:_
- [Version Release](?template=version_release.md)
- _Alternatively delete and start empty_
> Uppdate user guides

- app/assets/scripts/components/documents/single-view/document-body.js
Addresses: https://github.com/NASA-IMPACT/nasa-apt/issues/753
> Add reviewer info in the PDF type atbd

- app/assets/scripts/components/documents/document-tracker-modal.js
Adds help video for document transitions
Link to issue: https://github.com/NASA-IMPACT/nasa-apt/issues/618
> Add secondary button link to video

- content/strings/algorithm_description.yml
- content/strings/algorithm_usage.yml
From: https://github.com/NASA-IMPACT/nasa-apt/issues/802#issuecomment-1745494925, https://github.com/NASA-IMPACT/nasa-apt/issues/799#issuecomment-1737767100 and https://github.com/NASA-IMPACT/nasa-apt/issues/799#issuecomment-1739501940
> Update Mathematical Theory Tooltips

- app/assets/scripts/components/documents/journal-pdf-preview/index.js
- Sorts the contacts in the Journal PDF in the author headline
- Removes authors that have the "Document Reviewer" role from the authors list and corresponding authors list
> sort contacts for journal pdf and remove reviewers

- app/assets/scripts/components/documents/document-download-menu.js
- Handle API response when content is a blob on pdf download (#572)
> Production deployment

- app/assets/scripts/components/documents/journal-pdf-preview/index.js
- app/assets/scripts/components/documents/single-view/document-body.js
Reverts the sort method temporarily while we figure out another sorting mechanism.
Closes #574
> Revert corresponding author being listed first 

- app/assets/scripts/utils/references.js
Fixes issue when an author has multiple first names, removing the extra commas. See https://github.com/NASA-IMPACT/nasa-apt/issues/827
> adds support for multiple initials in author names

- app/assets/scripts/utils/references.js
Upstream: https://github.com/NASA-IMPACT/nasa-apt/issues/827
From https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/577#issuecomment-2004907190
> Re-add space in between multiple authors

- app/assets/scripts/components/common/page-footer.js
Fixes https://github.com/NASA-IMPACT/nasa-apt/issues/844
Adds accessibility statement to the footer
> add accessibility statement
