- app/assets/scripts/components/dashboard/index.js
- app/assets/scripts/context/user.js
- app/assets/scripts/main.js
Contribute to https://github.com/NASA-IMPACT/nasa-apt/issues/469
This PR adds the ability for the user to be logged in automatically once redirected from the hosted cofnito UI.
The library we're using to handle the congito comunication in the frontend ([AWS Amplify](https://aws.amazon.com/amplify/authentication)) does not support being initialized with a token.
If it manages the whole process (login with user and pwd) then it works fine - this is the normal flow we have implemented.
If, on the other hand, cognito UI handles the login then Amplify will not pick up on the token. This is why the user was not logged in.
After quite some digging I found an issue that talked about this [exact problem](https://github.com/aws-amplify/amplify-js/issues/825#issuecomment-496977827) and provided a …
> Login improvements

- app/assets/scripts/components/documents/single-edit/local-store.js
- app/assets/scripts/components/documents/single-edit/local-store/atbd-storage.js
- app/assets/scripts/components/documents/single-edit/local-store/index.js
- app/assets/scripts/components/documents/single-edit/local-store/recover-toast.js
- app/assets/scripts/components/documents/single-edit/step-algo-description.js
- app/assets/scripts/components/documents/single-edit/step-algo-implementation.js
- app/assets/scripts/components/documents/single-edit/step-algo-usage.js
- app/assets/scripts/components/documents/single-edit/step-closeout/index.js
- app/assets/scripts/components/documents/single-edit/step-contacts/index.js
- app/assets/scripts/components/documents/single-edit/step-identifying-information.js
- app/assets/scripts/components/documents/single-edit/step-introduction.js
- app/assets/scripts/components/documents/single-edit/step-references/index.js
Resolves https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/340
- I implemented the functionality into a React component `LocalStore`, which is added to each of the Formik instances of the editor. Placing the component inside Formik allows us to listen to value changes in any of the form's fields and act accordingly. 
- When a form is initialised, we look for a value in local storage and merge with the values taken from the form state, with values from local storage taking precedence. 
- If the values from local storage are for a different step, we take the original form values without merging and we clear the local storage. This is in line with the current behaviour where you lose changes when moving to another step without saving. 
- If the current form is `dirty`, ie. values have …
> Save and load from local store

- app/assets/scripts/components/documents/single-edit/index.js
- app/assets/scripts/components/documents/single-edit/step-algo-description.js
- app/assets/scripts/components/documents/single-edit/step-algo-implementation.js
- app/assets/scripts/components/documents/single-edit/step-algo-usage.js
- app/assets/scripts/components/documents/single-edit/step-closeout/index.js
- app/assets/scripts/components/documents/single-edit/step-contacts/index.js
- app/assets/scripts/components/documents/single-edit/step-identifying-information.js
- app/assets/scripts/components/documents/single-edit/step-introduction.js
- app/assets/scripts/components/documents/single-edit/step-references/index.js
- app/assets/scripts/components/documents/single-edit/steps.js
- app/assets/scripts/components/documents/single-edit/use-submit.js
This PR adds introduces wizard-like functionality to the ATDB form, allowing users to save the form and redirect to the next step in the form. Contributes to #476
- Adds function `getNextDocumentEditStep`, which returns the following step ID from the current one. 
- Adds `SaveAndContinueButton`, which submits the form and redirects to the next step if the form has been submitted successfully. 
- Adds new prop `renderFormFooter` to form components, which we use to render the `SaveAndContinueButton` into each form.
- Returns results from the following submit handlers, so we know when `SaveAndContinueButton` needs to redirect to the next step:
- `useSubmitForMetaAndVersionData`
- `useSubmitForVersionData`
- `useSubmitForAtbdContacts`
> Add save-and-continue button to document form

- app/assets/scripts/components/documents/single-edit/step-closeout/index.js
- app/assets/scripts/components/documents/single-edit/steps.js
- app/assets/scripts/components/documents/single-view/document-body.js
Implements https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/331
- Changes `abstract` and `plain_summary` to `FormikInputEditor` fields.
- Adds a new function to count words for rich-text fields.
- Changes how `abstract` and `plain_summary` are rendered in the document view mode
How to test:
- Run these changes against the [corresponding backend changes](https://github.com/NASA-IMPACT/nasa-apt/pull/496)
> Change plain_summary and abstract to rich text fields

- app/assets/scripts/components/slate/editor.js
- app/assets/scripts/components/slate/plugins/equation/equation-editor.js
- app/assets/scripts/components/slate/plugins/equation/equation-element.js
- app/assets/scripts/components/slate/plugins/equation/equation-modal.js
- app/assets/scripts/components/slate/plugins/equation/index.js
- app/assets/scripts/components/slate/plugins/equation/with-equation-modal.js
Resolves [#501](https://github.com/NASA-IMPACT/nasa-apt/issues/501)
Refactors equation editing so the editor form is shown in a modal
- Adds a new option 'edit' to the context menu, clicking the button will open the equation editor in a modal
- Removes to cheatsheet link from the context menu and moves it into the modal
> Equation popup

- app/assets/scripts/components/documents/single-edit/local-store/index.js
Fixes https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/363
If the user doesn't close the recover-data toast, the toast is displayed on every change event within the pages leading to several toast being shown on the page. 
Changes to fix:
- We're tracking the ID of the toast that is currently shown and only display a new toast of the toastID is falsy. 
- We're clearing the toastID once the toast has been hidden. 
Additionally:
- We're hiding the toast once the user starts changing the form. At this point, if the use recovers the data, the changes will be overwritten. This change assumes that the user does not want to recover the data once they start changing the data. @aboydnw let me know what you think of this.
> Show recover-data toast only once; automatically remove when user changes form data

- app/assets/scripts/components/common/forms/input-editor.js
- app/assets/scripts/components/documents/single-edit/step-closeout/index.js
- app/assets/scripts/components/slate/editor.js
Following the discussions in https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/364 we're removing the table and image plugins from the abstract field. 
- Adds new prop `excludePlugins` from `FormikInputEditor` and `RichTextEditor` which allows passing along an array of Slate plugins that should not be available to the instance.
- Extends `RichTextEditor` so plugins passed with `excludePlugins` are excluded
- Exclude table and image plugins from `FieldAbstract`
> Exclude tables and images from abstract field

- app/assets/scripts/components/slate/plugins/equation/equation-editor.js
- app/assets/scripts/components/slate/plugins/equation/equation-modal.js
This PR is set on top of #366 and normalizes the modal usage / reorders the buttons.
Although there was nothing wrong with the approach taken in #366, the button controls on APT have been set in the modal footer aligned to the left (or center in small modals). See for example the reference modal:
https://github.com/NASA-IMPACT/nasa-apt-frontend/blob/fec79ebc427a240be958b98b4a5a84d7120b3850/app/assets/scripts/components/slate/plugins/reference/reference-modal.js#L114-L130
To achieve this I had to move some of the logic out of `EquationEditor` and into the `EquationModal`. Because it changes some of your code I didn't want to add it directly to the other PR. See what you think. If you want to change stuff around or just use some of the code, feel free.
> Equation modal normalization

- app/assets/scripts/components/common/unload-prompt.js
- app/assets/scripts/components/documents/single-edit/step-algo-description.js
- app/assets/scripts/components/documents/single-edit/step-algo-implementation.js
- app/assets/scripts/components/documents/single-edit/step-algo-usage.js
- app/assets/scripts/components/documents/single-edit/step-closeout/index.js
- app/assets/scripts/components/documents/single-edit/step-contacts/index.js
- app/assets/scripts/components/documents/single-edit/step-identifying-information.js
- app/assets/scripts/components/documents/single-edit/step-introduction.js
- app/assets/scripts/components/documents/single-edit/step-references/index.js
Implements https://github.com/NASA-IMPACT/nasa-apt/issues/455
- Adds two components
- `UnloadPrompt` a generic unload prompt that can be plugged in anywhere and will show a confirmation prompt whenever the page changes or the browser is closed or reloaded
- `FormikUnloadPrompt` uses the Formik context to set the `when` property of `UnloadPrompt`; can only be used within a Formik context
- Adds `FormikUnloadPrompt` to document editor forms
> Add warning before closing form with unsaved changes

- app/assets/scripts/components/common/confirmation-prompt.js
- app/assets/scripts/components/documents/single-edit/check-lock.js
- app/assets/scripts/components/documents/single-edit/index.js
Resolves https://github.com/NASA-IMPACT/nasa-apt/issues/454
Adds new component `CheckLog`, which encapsulates functionality to set locks on ATBD versions. 
- On mounting the component, checks if lock can set; redirects to version view if not.
- If the versions is locked, the a modal is shown, allowing authors to overwrite the lock. 
- On unmounting the component, clears the lock.
> Block simultaneous edit

- app/assets/scripts/components/documents/single-view/document-body.js
Fixes https://github.com/NASA-IMPACT/nasa-apt/issues/542
- Adds a permissions check to the `hasCommentButton` flag
- Pass the ATBD object for the permissions check
**How to test**
Use the public ATDB http://localhost:9000/documents/test-atbd-1/v1.1
Switch to different users and check of the comment button shows when you hover over a headline
- Owner Olivia should see the button
- Andre Author should see the button
- Allison Auth should not see the button
Log out completely, you should have access to the ATDB but not see the button
> Show comment button only to authorized users

- app/assets/scripts/components/comment-center/comment-form.js
- app/assets/scripts/components/comment-center/thread-list-panel.js
- app/assets/scripts/components/comment-center/thread-single-panel.js
- app/assets/scripts/context/comment-center.js
- app/assets/scripts/context/threads-list.js
Contributes front-end implementation for https://github.com/NASA-IMPACT/nasa-apt/issues/456
- Adds a new field to the comment that allows to select people for notification about the comment. 
- The list of people included for selection includes all contributers (owner, reviewers, authors) of the document.
- People selected for notification are persisted and pre-populated for responses to the comment.
Test this together with https://github.com/NASA-IMPACT/nasa-apt/pull/544
> Comment mentions

- app/assets/scripts/components/documents/single-edit/step-closeout/journal-details.js
- app/assets/scripts/components/documents/status.js
Contributes to https://github.com/NASA-IMPACT/nasa-apt/issues/480
Removes any restrictions from the publication-status radio buttons, authors can now change the publication status independent of the ATBD status. 
For testing, run [this branch](https://github.com/NASA-IMPACT/nasa-apt/pull/550) in the backend
> Allow update publication status for all ATBD status

- app/assets/scripts/components/documents/document-versioning-process.js
- app/assets/scripts/components/documents/single-edit/document-minor-version-reminder.js
Contributes to [#480](https://github.com/NASA-IMPACT/nasa-apt/issues/480)
- Changes the modal and button text
- Decided not to change the button label to confirm, because button labels describing the actual action are better
> Updates version-update modal text

- app/assets/scripts/a11n/rules.js
- app/assets/scripts/components/dashboard/document-list-settings.js
- app/assets/scripts/components/dashboard/use-document-menu-action.js
- app/assets/scripts/components/documents/document-governance-action.js
- app/assets/scripts/components/documents/use-document-modals.js
- app/assets/scripts/context/atbds-list.js
Front-end changes for https://github.com/NASA-IMPACT/nasa-apt/issues/480
- Removes the in-publication document status, and UI components
- Adapts permissions so ATBD can be made public after requesting publications
Test together with https://github.com/NASA-IMPACT/nasa-apt/pull/553
> Remove in-publication step

- app/assets/scripts/components/dashboard/document-list-settings.js
- app/assets/scripts/components/dashboard/index.js
- app/assets/scripts/components/documents/document-tracker-modal.js
- app/assets/scripts/components/documents/status.js
Contributes to https://github.com/NASA-IMPACT/nasa-apt/issues/480
- Removes the "In Publication status" and all adjacent functionality from the code base
- Renames status "Published" to "Public"
> Remove in-publication status

- app/assets/scripts/components/documents/document-changelog-modal.js
Fixes a bug with the changeling modal.
**Problem**
The current version in the `versions` array doesn't include the `document` after updating the ATBD. That's why we're seeing a fatal error because the version changeling tries to read the `document` value and can't find it. 
**How to test**
- Edit an ATBD
- Save
- Saving should not cause an error
> Read version description of current version from ATBD

- app/assets/scripts/components/common/toasts.js
- cypress/e2e/document/publish-workflow.js
- cypress/fixtures/server/atbd-event.json
- cypress/fixtures/server/atbd-reviewer-list.json
- cypress/fixtures/server/atbd-versions.json
- cypress/fixtures/server/atbd.json
- cypress/support/login.js
The PR adds tests for the following scenarios:
- Request a review
- Cancel a review
- Approve/Deny a review
- Conclude review
- Request publication
- Publish document
Also makes changes to the long command to
- set the correct user ids
- be able to select different user roles
> Add publish-workflow tests

- app/assets/scripts/context/comment-center.js
- app/assets/scripts/utils/references.js
The api to get the values from the bibtex was not properly implemented and the DOI field was being excluded.
This PR changes the import format and api fixing the problem
> Support DOI field when importing references from bibtex

- app/assets/scripts/components/documents/document-download-menu.js
Makes sure that while downloading a PDF, the toasts don't stack up like this:
> Make the toasts a bit less awkward

- .github/workflows/build.yml
- Dockerfile
Add a Dockerfile and a GitHub action to build and push the docker image to the GitHub container registry.
As part of the new PDF generation process in https://github.com/NASA-IMPACT/nasa-apt/pull/638, we run the frontend as a docker-compose service in the development environment. Uploading a docker image of the frontend to Github's container registry ensures that we can pull and use an existing image instead of having to build the frontend image locally for backend development.
> Dockerize the ui

- .github/workflows/build.yml
fixes the [failing docker build](https://github.com/NASA-IMPACT/nasa-apt-frontend/actions/runs/4465565353/jobs/7842749413#step:4:5) by making `NASA-IMPACT` lowercase.
> lowercase organization name for docker repository

- app/assets/scripts/components/documents/single-edit/step-identifying-information.js
Bug #404 reveals that the `RichTextContext2Formik` context provider was not added to the first step in the document edit form. By adding this context, we fix the dependent bugs like the image upload.
Props to @danielfdsilva for figuring it out.
> Add rich context to 1st step in form

- .npmrc
- yarn.lock
Apt used a private DS registry for npm packages which was causing the build to break and is no longer needed.
> Fix npm registry

- app/assets/scripts/components/documents/document-download-menu.js
Upstream: https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/451
Increases the time that PDFs can try to generate before succeeding/failing. We can reduce the increased numbers if they're too extreme or cause issues elsewhere
> Increase PDF retry amount and 201 timeout

- app/assets/scripts/utils/references.js
Upstream: https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/446#issuecomment-1496418743
Removes spaces between authors in the reference section when two or more authors are present.
> Add spaces between authors in reference section

- app/assets/scripts/components/documents/document-download-menu.js
Upstream: https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/451#issuecomment-1498709846, https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/452
Further increases time that the Document PDF can generate before a user is given an error message (250s).
> Increase retry count for PDF generation delivery

- app/assets/scripts/components/documents/document-download-menu.js
Note:  We're using [`file-saver`](https://www.npmjs.com/package/file-saver) to download the pdf. And from the documentation
Which means we'll still get and CORS error (at least in the development mode) but it'll download afterwards using the anchor element.
We can solve this issue by updating the CORS policy in the s3
> Update pdf download mechanism

- app/assets/scripts/components/documents/document-governance-action.js
Contributes to [#632](https://github.com/NASA-IMPACT/nasa-apt/issues/632)
@wrynearson I tried adding an Exit Editing button but because of the Step Counter it didn't fit well in the header.
> Adds separate Edit Button 

- app/assets/scripts/components/documents/document-download-menu.js
* Fix for https://github.com/nasa-impact/nasa-apt/issues/744
* Temporarily set `canDownloadJournalPDF` to false until Journal PDF functionality is fixed
> Temporarily disable Journal PDF download

- app/assets/scripts/components/dashboard/dash-contributor.js
Reuse create document button on the dashboard page when the user doesn't have any documents yet.
refs https://github.com/NASA-IMPACT/nasa-apt/issues/754
> Reuse create document button

- app/assets/scripts/components/documents/document-download-menu.js
Upstream: https://github.com/NASA-IMPACT/nasa-apt/issues/770
Reviewer should:
> Add blocked popup text to PDF download success toast

- app/assets/scripts/components/documents/single-edit/step-references/references-manager.js
The state of the modal depends on the variables `selectedReferencesList` and `editingReferencesList`, selection lists that depend on the state variables `refsSelected` and `refsEditing` respectively. However, when toggling the edit button or selection checkboxes, the state variables are edited but the dependent variables are not changed. This is because the field itself never re-renders.
I wrote a hack (should not impact performance) that touches the internal array of the form but does not modify it using `move(index, index)`. This forces the field to re-render. I'm sure there are better ways of doing this, but it might require a re-architecting of the state variables in this module.
> Fix Reference Edit and Select buttons

- app/assets/scripts/components/slate/plugins/reference/reference.js
Changes the ref font size to match the rest of the body text:
> change ref font-size

- app/assets/scripts/components/documents/single-view/document-body.js
Upstream: https://github.com/NASA-IMPACT/nasa-apt/issues/682#issuecomment-1614721128
> Move Journal Details section above Contacts section

- package.json
- tests/README.md
Adds documentation for Playwright tests in the frontend. The information is a little dense but I tried to simplify it as much as possible. Please let me know if there is a topic you would like me to expand on because I think this could be a good internal documentation for us using Playwright @wrynearson @sunu
To merge:
1. Read the documentation
2. Try running tests
3. If any information does not make a lot of sense please let me know so I can rewrite it.
> Add test documentation

- app/assets/scripts/components/dashboard/document-dashboard-entry.js
- app/assets/scripts/components/documents/document-headline.js
- app/assets/scripts/components/documents/hub/document-hub-entry.js
- app/assets/scripts/components/documents/new-atbd-modal.js
- app/assets/scripts/components/documents/single-edit/step-identifying-information.js
- app/assets/scripts/components/documents/single-view/document-title.js
- app/assets/scripts/utils/common.js
- content/strings/identifying_information.yml
Title parse in:
Addresses: https://github.com/NASA-IMPACT/nasa-apt/issues/586
> Parse latex equation int the format {{~equation~}}

- app/assets/scripts/components/documents/document-tracker-modal.js
Updates the text for the welcome modal according to https://github.com/NASA-IMPACT/nasa-apt/issues/756
The following shows a modal for a PDF mode document:
According to the document the step workflow was the same so all I did was modify the text conditionally depending on the document type.
> Update document modal for PDF mode

- app/assets/scripts/components/documents/single-edit/use-document-create.js
More readable messages when getting create errors from the server: the user knows that a document alias is not available when submitting a form with the same title.
Addresses https://github.com/NASA-IMPACT/nasa-apt/issues/779
> Get create errors from server

- app/assets/scripts/a11n/signin.js
- app/assets/scripts/components/common/forms/form-info-tooltip.js
This adds a tooltip for the MFA setup according to https://github.com/NASA-IMPACT/nasa-apt/issues/801#issuecomment-1733107556
The modal will look like this:
> Add MFA tooltip

- app/assets/scripts/components/documents/journal-pdf-preview/index.js
- app/assets/scripts/components/documents/single-view/document-body.js
- app/assets/scripts/components/slate/plugins/caption/caption.js
- app/assets/scripts/utils/format-table-captions.js
Contributes to https://github.com/NASA-IMPACT/nasa-apt/issues/681.
Before generating the PDFs, apply `formatDocumentTableCaptions()` to the document in order to compute table numbers and move the caption before the table.
To test, run the app locally using the staging API and visit:
- http://localhost:9000/documents/test/v1.0/pdf-preview
- http://localhost:9000/documents/test/v1.0/journal-pdf-preview
Or create a new document with tables in different sections.
> Add table numbers

- app/assets/scripts/components/documents/journal-pdf-preview/index.js
Fix for corresponding authors and for author headers https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/421#issuecomment-1759332037
> Add corresponding authors

- app/assets/scripts/components/documents/journal-pdf-preview/index.js
- app/assets/scripts/components/documents/single-view/document-body.js
- app/assets/scripts/types.js
This adds missing sections (3.3 and 3.4) to journal PDF, as reported [in this comment](https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/421#issuecomment-1758011668).
Additionally, I've initiated a types.js file to house common type definitions, which I find beneficial for identifying data structures throughout the app.
@kamicut @sunu ready for review.
> Add algorithm variables to the journal pdf

- app/assets/scripts/components/documents/document-delete-process.js
- app/assets/scripts/components/documents/single-edit/use-document-create.js
- app/assets/scripts/components/documents/single-edit/use-submit.js
- app/assets/scripts/components/new-atbd/index.js
Contributes to https://github.com/NASA-IMPACT/nasa-apt/issues/807.
Changes:
- Add custom events to successful ATBD creation, update and deletion
- Add custom event to ATBD template downloads by format
How to test:
- Copy staging tracking code `config/local.js`
- Run the app locally
- Create documents, both regular and PDF upload
- Update and delete documents
- Go to GA dashboard
- Click "Reports" and "Realtime" in the left vertical bar
- Your events should be listed in `Event count by Event name` panel
- Click `atbd_created` event, it should include a property named `type` equal `pdf`and one equal to `regular`
- Click `atbd_template_download` it should include a property called `template_format` with the number of times each template format was downloaded
Please note the "Lifecycle" panel …
> Enhance collected metrics (atdb edits, template download)

- app/assets/scripts/components/documents/journal-pdf-preview/index.js
- app/assets/scripts/components/documents/pdf-preview/index.js
- app/assets/scripts/components/documents/single-view/document-body.js
- app/assets/scripts/utils/apply-number-captions-to-document.js
- app/assets/scripts/utils/format-table-captions.js
This fixes a regression introduced in https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/549 (reported [here](https://github.com/NASA-IMPACT/nasa-apt/issues/681#issuecomment-1753109122)) where the captions and number for images and equations disappeared in the document PDF preview. 
Please note this PR only reinstates the preexisting number in document PDF preview. The following issues are still present:
- Document preview: image and table captions positioned at the bottom
- Journal preview: images caption positioned at the bottom
I suggest we handle those separately as they look more involved.
To test, open a document in document preview mode and confirm numbers are present for images, equations, and tables. Example:
- http://localhost:9000/documents/links/v1.0/pdf-preview
cc …
> Fix equations and images captions in document PDF preview

- app/assets/scripts/components/slate/plugins/caption/caption.js
- app/assets/scripts/context/numbering.js
- app/assets/scripts/utils/apply-number-captions-to-document.js
Address issue raised at https://github.com/NASA-IMPACT/nasa-apt/issues/681#issuecomment-1766607719.
This changes the transformer function `applyNumberCaptionsToDocument` to revert caption position only for table blocks. I've also removed code related to tables and figures from the numbering context, because it conflicts with the transformer. I've chosen to use the transformer instead of the numbering context for tables/figures captions because the later doesn't handle positioning.
@frozenhelium @wrynearson this is ready for review. Please confirm if tables are position above and figures below on PDF previews.
> Fix figure caption position

- app/assets/scripts/components/slate/plugins/equation/equation-element.js
This changes the equation component to use the element path instead of its content to determine uniqueness. Should fix issue reported at https://github.com/NASA-IMPACT/nasa-apt/issues/681#issuecomment-1766533111. 
To test, add multiple empty and non-empty equations to a document and check if the number is incrementing without repetition.
@wrynearson @frozenhelium ready for review.
> Fix equation number repetition

- app/assets/scripts/components/documents/single-view/document-body.js
Upstream: https://github.com/NASA-IMPACT/nasa-apt/issues/753
- Removes the reviewer information for both the journal PDFs and the document PDF in print mode.
- Keeps the reviewer information when viewing the document in "HTML mode"
> Remove reviewer info in the PDFs

- app/assets/scripts/a11n/forbidden.js
- app/assets/scripts/components/new-atbd/index.js
How to test: visit 'Create ATDB' page at http://localhost:9000/new-atbd, it shouldn't display 'Sign in' message if the user is logged in.
I also included the same API change in the 'Forbidden' page, but it is not clear to me how to get to desired state. 
@kamicut ready for review.
> Fix auth messages in 'create atbd' pages

- app/assets/scripts/components/new-atbd/index.js
Contributes to https://github.com/NASA-IMPACT/nasa-apt/issues/807.
In https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/563 we added custom events for tracking template downloads by format, but it seems the event parameter `template_format` is not persisted after some time in the GA dashboard.
In this PR I moved the format to the event name, which should allow tracking download events by format older than 30 mins.
How to test:
- Replace config/local.js with the content of config/staging.js
- Run the app
- Visit http://localhost:9000/new-atbd and download each of the available formats
- Visit GA dashboard
- Go to Reports -> Realtime
- Box 'Event count' by 'Event name' should list the new event names:
- `atbd_template_download_google_docs`
- `atbd_template_download_ms_word`
- …
> Move the template format to the event name (Google Analytics)

- app/assets/scripts/components/documents/document-download-menu.js
Download for uploaded ATBD PDFs is not working because the API response is different from regular ATBDs. This PR fixes this issue.
How to test:
- Setup staging API in config/local.json
- Visit localhost:9000
- All PDF downloads in the list should work (both regular and uploaded PDFs, the last has a pdf icon beside it)
cc @sunu
> Fix uploaded PDFs download

- app/assets/scripts/components/documents/citation.js
- app/assets/scripts/utils/references.js
The document info modal uses the `identifying information` step and formats the author, publisher and DOI into a citation.
Upstream ticket: https://github.com/NASA-IMPACT/nasa-apt/issues/825
Here's what's fixed:
> Fix document info modal citation
